name: build_push

on: [push]

jobs:
  run_molecule_test:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        distro:
          - image: ubuntu
            version: "bionic"
            platform: "linux/amd64,linux/arm64"
            tags: "bionic"
          - image: ubuntu
            version: "focal"
            platform: "linux/amd64,linux/arm64"
            tags: "focal"
          - image: ubuntu
            version: "jammy"
            platform: "linux/amd64,linux/arm64"
            tags: "jammy"
          - image: ubuntu
            version: "noble"
            platform: "linux/amd64,linux/arm64"
            tags: "noble,latest"
    uses: hybridadmin/reuse-workflows/.github/workflows/build_push.yml@main
    secrets: inherit
    with:
      distro_image: '${{ matrix.distro.image }}'
      distro_tags: '${{ matrix.distro.tags }}'
      distro_platform: '${{ matrix.distro.platform }}'
      distro_version: '${{ matrix.distro.version }}'

  run_update_readme:
    needs:
      - run_molecule_test
    uses: hybridadmin/reuse-workflows/.github/workflows/update_readme.yml@main
    secrets: inherit
    with:
      repo_name: 'hybridadmin/ansible-ubuntu'
